### ISSUE TITLE
Unspecified dependency on ConfigParser

### ISSUE THREAD

**Issue by eljobe** [RedMoonStudios/hetzner#16]
When I run `./hetznerctl` from within the cloned source directory, it works as expected.

However, when I install it with `pip install hetzner` or by running `python setup.py install` in the cloned source directory, and then just run `hetznerctl` from the command line I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/hetznerctl", line 7, in <module>
    from ConfigParser import RawConfigParser, Error
ImportError: No module named 'ConfigParser'
```

This only happens with python 2.x.

With the following commands I get a happy installation:
```
$> python3 setup.py install
$> /Library/Frameworks/Python.framework/Versions/3.5/bin/hetznerctl list
```

I'm cautious just to put that bin directory on my PATH before the corresponding python2 directory because I think OS X maybe expecting certain python tools to be written in python2.

The specific versions of python I am using are:
```
$> python --version
Python 2.7.12

$> python3 --version
Python 3.5.2
```

Please advise.

**Comment by aszlig** [comment]
Hm, `ConfigParser` should be in the Python 2.7.x standard library. What's the shebang of `/usr/local/bin/hetznerctl`?

**Comment by eljobe** [comment]
Right now, it's:
`#!/usr/local/opt/python3/bin/python3.5`

But, I just installed it with python 3.5.2. I'm happy with that workaround and I don't really have time to make a reproduction case for the 2.7 version (really sorry).  So, you can either:

1. simply close this issue
2. attempt to reproduce the problem on your own

**Comment by aszlig** [comment]
@eljobe: I can't reproduce this, at least with Nix. If you manage to reproduce the problem again, please feel free to re-open the issue.
