### ISSUE TITLE
Branching/tags question

### ISSUE THREAD

**Issue by nh2** [RedMoonStudios/hetzner#22]
I noticed that the `robot.py` in the release tags `v0.7.4` and `v0.7.5` is different from what's on master:

* `v0.7.5`: https://github.com/RedMoonStudios/hetzner/commit/76a9faff601dd9e22e6934b80cffdba0876f9792
* `master`: https://github.com/RedMoonStudios/hetzner/blob/280f8d3105937d46da21d534f82315f83db3ed84/hetzner/robot.py

and strangely the `v0.7.5` has _newer_ changes than master.

Will these changes make it into `master`?

I'm trying to modify `hetzner` but I'm not quite sure on what base commit I should put my changes.

**Comment by nh2** [comment]
Also the `master` branch has important fixes such as https://github.com/RedMoonStudios/hetzner/commit/3039fec89f74618657db0509765dda48a090f0be which would greatly improve debugging (e.g. from nixops).

It would be great to have those landed.

**Comment by aszlig** [comment]
I'll soon release version `0.8.0` (which inclues 3039fec89f74618657db0509765dda48a090f0be) and also make a branch for `0.8.0` as well, so this should be less confusing.

So far the 0.7.x versions were tagged using a detached `HEAD`.
